
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('dreams').del()
    .then(function () {
      // Inserts seed entries
      return knex('dreams').insert([
        { title: 'Politics Dreams',
          description: 'Politician, news, current events',
          price: 50,
          genre: 'polictics',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=LK5fgW30HwE',
          dream_images: 'https://static.politico.com/dims4/default/0eebb66/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2F5b%2F8d%2F92d5038a468ab3b4b33e3eac12de%2F1-kal-the-baltimore-sun.jpg',
          store_id: 1,
          user_id: 1
        },
        { title: 'Kingdom Dream',
          description: 'Kings and Queens Dreams',
          price: 50,
          genre: 'theatrical',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=40qOAcz5bUM',
          dream_images: 'https://belmontpres.org/uploads/3/5/4/5/35451819/published/narnia-kings-and-queens.jpg',
          store_id: 2,
          user_id: 2
        },
        { title: 'Doggy Dreams',
          description: 'Dream about dogs',
          price: 50,
          genre: 'animals',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=qBGbVIL_HG8',
          dream_images: 'https://cdn.pixabay.com/photo/2017/08/17/15/34/pug-2651728_960_720.jpg',
          store_id: 3,
          user_id: 3
        },
        { title: 'Technology Dreams',
          description: 'Dreams about technology',
          price: 50,
          genre: 'technology',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=tqKpk1wABuI',
          dream_images: 'https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/07/Philips-AI-796x531.jpg',
          store_id: 4,
          user_id: 4
        },
        { title: 'Despacito Dream',
          description: 'Dream about Despacity Song',
          price: 50,
          genre: 'music',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=R9yNWbetJVU',
          dream_images: 'https://nigezie.tv/wp-content/uploads/2017/06/justin-bieber-despacito-remix-2.png',
          store_id: 5,
          user_id: 5
        },
        { title: 'Billionaire',
          description: 'Billionaire Dreams',
          price: 50,
          genre: 'wishful',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=8aRor905cCw',
          dream_images: 'https://spikeybits.com/wp-content/uploads/2017/08/gold-wal-hor.jpg',
          store_id: 6,
          user_id: 6
        },
        { title: 'Comedy',
          description: 'Comedy Dreams',
          price: 50,
          genre: 'comedies',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=yOSnT2XKGE8',
          dream_images: 'https://bloximages.chicago2.vip.townnews.com/pressofatlanticcity.com/content/tncms/assets/v3/editorial/d/65/d65d1c96-a9a1-530a-aa9c-6a4fd606741a/57ea808bbbc93.image.jpg',
          store_id: 7,
          user_id: 7
        },
        { title: 'Frankenstein',
          description: 'Frankenstein Dreams',
          price: 50,
          genre: 'monsters',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=pBzONIqutBA',
          dream_images: 'http://humanities.drury.edu/wp-content/uploads/2016/01/Picture1.jpg',
          store_id: 8,
          user_id: 8
        },
        { title: 'Chopped Up',
          description: 'Bloddy chop chops',
          price: 50,
          genre: 'horror',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=H4rKlI42nSE',
          dream_images: 'https://i2.wp.com/www.comicsbeat.com/wp-content/uploads/2017/10/HalloweenFeature.jpg',
          store_id: 9,
          user_id: 9
        },
        { title: 'Austin Powers',
          description: 'Dream about Austin Powers',
          price: 50,
          genre: 'movies',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=-63bT-_xZCE',
          dream_images: 'https://cdn.images.express.co.uk/img/dynamic/36/590x/austin-powers-4-957708.jpg',
          store_id: 10,
          user_id: 10
        },
        { title: 'Nightmare',
          description: 'Nightmare Dreams',
          price: 50,
          genre: 'horror',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=DwWnlUQk67M',
          dream_images: 'https://www.syfy.com/sites/syfy/files/styles/700x1240/public/wire/legacy/a-nightmare-on-elm-street-1984-movie-still-robert-englund-as-freddy-kruger.png',
          store_id: 11,
          user_id: 11
        },
        { title: 'Shakespear',
          description: 'Shakespear Dreams',
          price: 50,
          genre: 'movies',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=yClVlc_niac',
          dream_images: 'https://media.timeout.com/images/100653989/750/422/image.jpg',
          store_id: 12,
          user_id: 12
        },
        { title: 'Harsh',
          description: 'Harsh Dreams',
          price: 50,
          genre: 'mood',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=b246fPvBvT0',
          dream_images: 'https://img.timesnownews.com/story/1539523120-Thinkstock_harsh_parenting_2.jpg',
          store_id: 13,
          user_id: 13
        },
        { title: 'Treasures',
          description: 'Treasure Dreams',
          price: 50,
          genre: 'treasures',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=ddtqcXo5ydk',
          dream_images: 'http://philippineslifestyle.com/wp-content/uploads/Screen-Shot-2017-08-30-at-4.02.20-pm.png',
          store_id: 14,
          user_id: 14
        },
        { title: 'Cats',
          description: 'Cat Dreams',
          price: 50,
          genre: 'animals',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=XyNlqQId-nk',
          dream_images: 'http://catsatthestudios.com/wp-content/uploads/2017/12/12920541_1345368955489850_5587934409579916708_n-2-960x410.jpg',
          store_id: 15,
          user_id: 15
        },
        { title: 'Dolls',
          description: 'Scary Dolls',
          price: 50,
          genre: 'stuff',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=t_QEu9eYycE',
          dream_images: 'https://images-na.ssl-images-amazon.com/images/I/91PPC-iArYL._SL1500_.jpg',
          store_id: 16,
          user_id: 16
        },
        { title: 'Any Kind',
          description: 'Any Kind of Dreams',
          price: 50,
          genre: 'any',
          duration: '8h 20m 05s',
          featured_video: 'https://www.youtube.com/watch?v=jgy5nO1DSoo',
          dream_images: 'https://previews.123rf.com/images/zodchiy/zodchiy1509/zodchiy150900006/44875574-the-quiet-calm-small-towm-street-with-different-kind-of-colorful-houses-fully-vector-illustration-.jpg',
          store_id: 17,
          user_id: 17
        }
      ]);
    });
};
